# Generated by Django 6.0.6 on 2026-07-04 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код продукта')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('package', models.CharField(choices=[('bottle', 'Бутылка'), ('pack', 'Пакет'), ('box', 'Коробка'), ('can', 'Банка'), ('bag', 'Мешок'), ('weight', 'Развес (без упаковки)')], default='pack', max_length=20, verbose_name='Вид упаковки')),
                ('arrival_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('shelf_life_days', models.PositiveIntegerField(default=30, verbose_name='Срок хранения, дней')),
                ('purchase_volume', models.PositiveIntegerField(default=0, verbose_name='Объём закупки')),
                ('sale_volume', models.PositiveIntegerField(default=0, verbose_name='Объём продажи')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена, руб.')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
