# Generated by Django 6.0.6 on 2026-07-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted',
            field=models.BooleanField(default=False, verbose_name='Уценён'),
        ),
    ]
